spring:
  application:
    name: monitor
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/monitor}
    username: ${DB_USERNAME:monitor}
    password: ${DB_PASSWORD:monitor}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8080}
